name: Java CI with Maven

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Job:
    runs-on: windows-latest
    steps:
      - name: Convert Markdown to HTML
        uses: natescherer/markdown-to-html-with-github-style-action@v1
        with:
          path: xx/yuwen.md
          outputpath: xx
