name: Build MD

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0
    - name: Converts Markdown to HTML
      uses: jaywcjlove/markdown-to-html-cli@main
      with:
        source: xx/yuwen.md
        output: xx/yw.html
        description: 一年级语文资料
        title: 一年级语文资料
        corners : false
        favicon: ../ico/favicon-32x32-yuwen.png
    - name: Converts Markdown to HTML
      uses: jaywcjlove/markdown-to-html-cli@main
      with:
        source: xx/yingyu.md
        output: xx/yy.html
        description: 一年级英语资料
        title: 一年级英语资料
        corners : false
        favicon: ../ico/favicon-32x32-yingyu.png
    - name: Converts Markdown to HTML
      uses: jaywcjlove/markdown-to-html-cli@main
      with:
        source: xx/kebiao.md
        output: xx/kb.html
        description: 课表
        title: 课表
        corners : false
    - name: Converts Markdown to HTML
      uses: jaywcjlove/markdown-to-html-cli@main
      with:
        source: README.md
        output: index.html
        description: 目录
        title: 目录
        corners : false
    - name: Converts Markdown to HTML
      uses: jaywcjlove/markdown-to-html-cli@main
      with:
        source: xx/grade1/cuoti/shuxue.md
        output: xx/grade1/cuoti/shuxue.html
        description: 数学错题
        title: 数学错题
        corners : false
    - name: Converts Markdown to HTML
      uses: jaywcjlove/markdown-to-html-cli@main
      with:
        source: xx/grade1/cuoti/yuwen.md
        output: xx/grade1/cuoti/yuwen.html
        description: 语文错题
        title: 语文错题
        corners : false
    - name: Commit files
      run: |
        git config --local user.email "andyBot@1659.us.kg"
        git config --local user.name "andyBot"
        git add -A
        git commit -a -m "Add changes"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: main

